spring.application.name=financialAssistant

spring.datasource.url=jdbc:mysql://localhost:3306/financialAssistant?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ollama Local Configuration
ollama.base-url=http://localhost:11434
ollama.model-name=llama3.2