spring.application.name=financialAssistant


spring.datasource.url=jdbc:mysql://localhost:3306/financialAssistant?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google Gemini API Key Configuration
langchain4j.google-ai-gemini.chat-model.api-key=YOUR_GEMINI_API_KEY
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.5-flash